name: randomTP
version: '${project.version}'
main: org.sabbelsocke.randomtp.RandomTP
api-version: '1.20'
load: STARTUP
commands:
  randomtp:
    description: Random teleport to a safe location in the current World
    usage: /rtp or /randomtp
    aliases:
      - rtp
